name: bart
description: A simple AI agent.
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  file: ^7.0.1
  http: ^1.5.0
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  test_api: ^0.7.7
